name: ipaw-0.3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2019.07.03
  - bioconda::msstitch=2.18
  - conda-forge::biopython=1.72
  - bioconda::percolator=3.1
  - bioconda::blast=2.9.0
  - bioconda::pybigwig=0.3.17
  - bioconda::pysam=0.15.3
    # annovar
  - conda-forge:perl=5.26.2
    # SpecAI
  - conda-forge::r-protviz=0.4.0
  - bioconda::bioconductor-msnbase=2.10.1
